# Top-level configuration
name = "sub-converter"
compatibility_date = "2025-07-31"
[assets]
directory = "./worker"
workers_dev = false
route = { pattern = "api-cdn.ning.host/justmysocks*", zone_name = "api-cdn.ning.host" }

kv_namespaces = [
  { binding = "<MY_NAMESPACE>", id = "<KV_ID>" }
]